[package]
name = "vmswitch"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = { version = "0.20.0", default-features = false, features = ["maplit", "term_size", "crossterm-backend"] }
virt = { path = "libvirt-rust" }
