unstable_features = true
max_width = 80
edition = "2021"
blank_lines_upper_bound = 2
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
combine_control_expr = false
condense_wildcard_suffixes = true
